### ISSUE TITLE
Item's single page layout

### ISSUE THREAD

**Issue by mateuswetah** [tainacan/tainacan-theme#16]
Just noticed there is no issue for this. Item's single page has a new header layout for a couple of months now, it is available on the design team google drive. 

You can ignore menu and breadcrumb position, it's on the old layout.

The color is the same color of the collection.

![image](https://user-images.githubusercontent.com/1184874/55639098-0366dc00-579f-11e9-8cc1-b28aac15ee98.png)

**Comment by leogermani** [comment]
Bringing this issue up with few more things:

I feel that our item's page is a dead end today. There is no links to keep browsing the collection. User often have to click Back to find another item...

suggestions

- [ ] More emphasis to the collection name and link (I think this is what this layout does, right?)
- [ ] Link to previous/next items in the collection?
- [ ] Link to other items with something in common?

Maybe this links to other items could be configured in Customizer
