### ISSUE TITLE
Blank space on tainacan items that attach WordPress pages

### ISSUE THREAD

**Issue by johanpdr** [tainacan/tainacan-theme#17]
![image](https://user-images.githubusercontent.com/6567563/55650785-07095b80-57bd-11e9-81ec-4f40d6c23161.png)

**Comment by mateuswetah** [comment]
This is an issue with the embed responsive class on the plugin and it is finally solved via https://github.com/tainacan/tainacan/commit/681df239fa0d327968985fe5d4a8744c6cde9baf. Basically, the crazy padding is necessary to make embeded iframes such as YouTube responsive, but not all embeds contain an `<iframe`, for example Twitter ones are converted to `<bloqueote` Release 0.17 of the plugin shall include it.
