### ISSUE TITLE
Missing words/fields for translation

### ISSUE THREAD

**Issue by pwfels** [tainacan/tainacan-theme#29]
I tried to translate into german but some words are missing in your tainacan-interface.pot.
The following words are missing:
Archive (in the sidebar)
Viewing Items: 1 to 3 of 3 (under the articel)

Do you need more information to fix this issue?

**Comment by mateuswetah** [comment]
Hi @pwefels thanks for the comment!

I guess the `.pot` file is out of data because we started using http://translate.wordpress.org/ for translating our theme, it seemed more appropriate. Don't you want to try there?

You should be able to update the `.po` file using **poedit**, although. https://poedit.net/

**Comment by pwefels** [comment]
Hi
in the .pot file there is the line for "Viewing Items: 1 to 3 of 3" but the translation is not working.
In your code (single-functions.php) i found the following lines:
`<?php //translators: Example - Viewing Items: 1 to 12 of 345 ?>
<?php printf( __('Viewing Items: %1$d to %2$d of %3$d', 'tainacan-interface'), $count_max + 1, $count_max + $wp_query->post_count, $wp_query->found_posts ); ?>`

In your .pot file is the follwoing line:
`Viewing Items: %d to %d from %d`

Archive is not in the .pot file and i did not find the line in your code. I use the theme "Tainacan Interface" Version: 1.6. 
So i think if i use http://translate.wordpress.org/  it will not work too.

**Comment by mateuswetah** [comment]
@pwefels, I'm checking here... shouldn't it work with this one?
https://translate.wordpress.org/projects/wp-themes/tainacan-interface/de/default/?filters%5Bterm%5D=Viewing+Items&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

**Comment by pwefels** [comment]
No its not work.

**.pot file:**
![2020-03-10 07_32_11-de_DE po • Tainacan Interface - Poedit](https://user-images.githubusercontent.com/54172675/76285969-4b408e00-62a1-11ea-9baa-f64c30e27915.jpg)

**Website:**
![2020-03-10 07_32_21-Volksbank Stadion](https://user-images.githubusercontent.com/54172675/76285965-4aa7f780-62a1-11ea-84d9-4c3970c8e29c.jpg)

**single-functions.php**
![2020-03-10 07_33_25-C__Users_pweissenfels_Desktop_tainacan-interface-nightly_tainacan-interface_func](https://user-images.githubusercontent.com/54172675/76286046-775c0f00-62a1-11ea-907c-48864b4aafb0.jpg)

**Comment by leogermani** [comment]
I've tested it and here is what I found.

This particular line is inside `tainacan_pagination` function which is invoked in:

https://github.com/tainacan/tainacan-theme/blob/ca0fab80c7ce950240428d16f90928f964d11892/src/template-parts/loop-tainacan-collection.php#L34

https://github.com/tainacan/tainacan-theme/blob/ca0fab80c7ce950240428d16f90928f964d11892/src/template-parts/loop-tainacan-collection-table.php#L33

https://github.com/tainacan/tainacan-theme/blob/ca0fab80c7ce950240428d16f90928f964d11892/src/template-parts/loop-tainacan-collection-grid.php#L27

https://github.com/tainacan/tainacan-theme/blob/ca0fab80c7ce950240428d16f90928f964d11892/src/template-parts/loop.php#L51

This means this is only used in Collections archives and regular blog posts archives. This is not used in items lists.

== How to translate ==

Here is what I did locally and worked:

I've opened POEDIT.

Opened the `pt_BR.po` file that lives inside the `languages`

Clicked the `Update from source code` button to fetch new strings.

Found this string and translated it. 

It worked.

For another locale, you can make a copy of the `pt_BR` file with another name and edit its details in POEDIT.

I hope that helps.

Leo,,

**Comment by pwefels** [comment]
Thanks this helped for "Viewing Items..." !
But how can i translate "Archive" in the right sidebar? In the languages files there is no line for this. There is only:

- Archive by category "
- Daily Archives: %s
- Monthly Archives: %s
- Yearly Archives: %s

**Comment by mateuswetah** [comment]
Hi @pwefels where are you referring to? Isn't it something on the Tainacan Plugin Admin panel? Because in that case it would be on the plugin translation repo.

**Comment by mateuswetah** [comment]
@pwfels we are about to release a new version. Have you find any more issues related to the translation that you want us to take a look?

**Comment by pwfels** [comment]
@mateuswetah no thanks 👍
