### ISSUE TITLE
change phrasing "description not informed"?

### ISSUE THREAD

**Issue by Ambrosiani** [tainacan/tainacan-theme#35]
Hi, I'm currently working on a Swedish translation and have found some English phrases that perhaps should be changed.

For instance here:
https://github.com/tainacan/tainacan-theme/blob/2ecf645f201f66908e071e56a16e5608a3a9e8d5/src/template-parts/loop-tainacan-collection.php#L24

This is checking whether there's an excerpt or not. Perhaps change "Description not informed" to "No excerpt found"?

Should I submit proposed changes as pull requests?

**Comment by mateuswetah** [comment]
Hi @Ambrosiani!

Its great that you are working on the Swedish translation! Please feel free to open pull requests with your translation files or even with any suggestion regarding the English string (we are mostly Brazilian developers, so our phrases can have errors).

But in this situation in particular, I think that "Description" is the appropriate term. Because in the Tainacan Collection custom post type (the one registered by the Tainacan plugin), the excerpt is named "Description". That is how the admin interface also refers to it.

**Comment by Ambrosiani** [comment]
hi @mateuswetah, thx for the info! Ok, just a follow up q: I haven't seen the "not informed" phrasing anywhere else. Perhaps "Description not found" or "No description provided" in this case, what do you think?

We've added the Swedish translation directly in translate.wordpress.org:

* https://translate.wordpress.org/projects/wp-themes/tainacan-interface/sv/default/ (first pass almost done, will work on improvements)
* https://translate.wordpress.org/locale/sv/default/wp-plugins/tainacan/ (only some initial translations made)

**Comment by mateuswetah** [comment]
Hey, just remembered this here.

I agree with the "No description provided", it sounds better! Will close this as soon as I commit.

**Comment by mateuswetah** [comment]
@Ambrosiani I've been following your progress on the plugin translation, that is awesome. Please feel free to reach contact if you have any other doubts about the terminology. 

I should also tell you that we have an email list where we discuss any doubts and issues. If you ever want to get into it, just sent an email to tainacan-subscribe@lists.riseup.net. Most of the conversation happens in Portuguese but we already have some English speakers users popping up :)

Finally, although this is the only official so far, we're been working on some other themes to make them compatible with Tainacan special pages. Right now I'm playing with a Child theme of [Blocksy](https://wordpress.org/themes/blocksy/), which has great customization features:

- https://github.com/tainacan/blocksy-tainacan

But we have some projects with child themes of the [Rife free](https://wordpress.org/themes/rife-free/) theme and the [Veganos](https://wordpress.org/themes/veganos):

- https://github.com/tainacan/rife-free-child
- https://github.com/tainacan/tainacan-unb-covid-19/tree/not-unb

And of course, the Wiki should be here to help you with other issues as well:
https://tainacan.github.io/tainacan-wiki/#/

Good luck with the translation!
