### ISSUE TITLE
YouTube embed link doesnt show proprerly on item view 

### ISSUE THREAD

**Issue by johanpdr** [tainacan/tainacan-theme#5]
YouTube embed link doesnt show proprerly on item view 
![2018-11-12 1](https://user-images.githubusercontent.com/6567563/48367841-1a464e00-e699-11e8-8518-7ce339d5220e.png)
![2018-11-12](https://user-images.githubusercontent.com/6567563/48367842-1a464e00-e699-11e8-8309-4b259b2d3cf5.png)

**Comment by leogermani** [comment]
please share the link to youtube you used

**Comment by johanpdr** [comment]
https://youtu.be/CqT_gZ9hr7k
this link is setup has non-listed at YT

**Comment by leogermani** [comment]
Confirmed.

Something wrong in the theme. @fabianobn

**Comment by fabianobn** [comment]
Ok, I'll check.

**Comment by leogermani** [comment]
@fabianobn apparently videos are displaying that big margin below it again
