### ISSUE TITLE
Want to contribute to translation (french)

### ISSUE THREAD

**Issue by yblatti** [tainacan/tainacan-theme#60]
Hi,

We're a small local historical society, and would love to use tainacan (looks awesome!).

We're located in a french speaking region and want to contribute to [tainacan-theme](https://github.com/tainacan/tainacan-theme) by offering a french translation.

My questions are : 

* Would you accept this contribution ?
* If so. What's the process ? : 
  * Is it juste a matter of opening a PR with fr_FR.po & fr_FR.mo translated with poedit from tainacan-interface.pot ?
  * Or do you use a third party / sass tool ? Build chain specifics ?

Thanks for your feedback, and thanks for your great project !

**Comment by yblatti** [comment]
Hi,

Thanks a lot for your very detailed answer!

I'll start to suggest translations in my spare time.
I see that there's a lot of work, I'll try to onboard a friend to help :)

I'll come back on the discourse when I have some substantial content and require approval.

Have a great day, and thank you again !

**Comment by mateuswetah** [comment]
No problem and no worries @yblatti, we know it is a lot of work. Any contribution will be welcome!
